### ISSUE TITLE
Getting stuck on the Edit team page

### ISSUE THREAD

**Issue by przemo20** [HH-GAME-MM/HH-Labyrinth-Plus-Plus#1]
Steps to reproduce:
1. Go to the Love Labyrinth, start a battle (by clicking on the “Perform and skip battle!” button) **and lose it**
2. Click “OK!” on the “You lost!” screen
3. You will get redirected to the Edit team page – click the “Cancel” button (below “Validate”)
4. You are once again sent to the Edit team page, this time let's click on the “Validate” button

The page refreshes, but you're still stuck on the Edit team page (no matter how many times you validate the new team) – clicking the “Cancel” button during the Step 3 is what causes the bug.

**Comment by HH-GAME-MM** [comment]
Thank you for your report! It is fixed in the next version 0.9.3 that i will release later today.

What happens technically (your points expanded):
1. Go to the Love Labyrinth, start a battle (by clicking on the “Perform and skip battle!” button) and lose it
2. Click “OK!” on the “You lost!” screen
2.1. set window.redirectUrl to "/labyrinth-pre-battle.html?id_opponent=1"
3. You will get redirected to the Edit team page – click the “Cancel” button (below “Validate”)
3.1. set window.redirectUrl to "/edit-labyrinth-team.html" (BUG => This happens in Kinkoid's code, but it's not their fault. It is a situation that would not occur without the script)
3.2. last window.redirectUrl "/labyrinth-pre-battle.html" will be requested from the server but you will be instantly redirected to the Edit Team page, because you have no team
4. You are once again sent to the Edit team page, this time let's click on the “Validate” button
4.1. last window.redirectUrl "/edit-labyrinth-team.html" (Edit Team Page) will be requested from the server (loop from now on)

The solution:
In step 4: If window.redirectUrl is "/edit-labyrinth-team.html", the script changes it to "/labyrinth.html"
